/**
 * User-facing labels: full plain name + abbreviation.
 * Prefer these everywhere a short jargon chip would otherwise appear.
 */
export const LABELS = {
  neo: "Near-Earth Object (NEO)",
  neoMonitor: "Near-Earth Object Monitor (NEO)",
  impactProbability: "Impact Probability (IP)",
  impactProbabilityShort: "Impact Probability (IP)",
  torino: "Torino Scale (TS)",
  palermo: "Palermo Scale (PS)",
  palermoMax: "Palermo Scale Max (PS max)",
  palermoCum: "Palermo Scale Cumulative (PS cum)",
  diameter: "Diameter (Ø)",
  absoluteMagnitude: "Absolute Magnitude (H)",
  viYears: "Virtual Impactor Years (VI years)",
  virtualImpactors: "Virtual Impactors (VIs)",
  lastObs: "Last Observation (Last obs)",
  firstObs: "First Observation (First obs)",
  vInf: "Approach Speed v∞ (km/s)",
  vImp: "Impact Speed v_imp (km/s)",
  mass: "Mass (kg)",
  observations: "Observations (nobs)",
  method: "Orbit Determination Method (Method)",
  sigmaVi: "Sigma Virtual Impactor (σ VI)",
  impactEnergy: "Impact Energy (Mt TNT)",
  originOrbit: "Orbit Origin — Small-Body Database (SBDB)",
  orbitClass: "Orbit Class (SBDB)",
  semiMajor: "Semi-major Axis (a)",
  eccentricity: "Eccentricity (e)",
  inclination: "Inclination (i)",
  periAp: "Perihelion / Aphelion (q / Q)",
  dataArc: "Observation Arc (Arc days)",
  moid: "Minimum Orbit Intersection Distance (MOID)",
  minImpactProb: "Minimum Impact Probability (Min IP)",
  dataAsOf: "Data as of",
  meteors: "Meteors",
  newBadge: "New Discovery (NEW)",
  trajectory: "Trajectory",
  fireballs: "Fireballs (FB)",
  fireballsMap: "Recent Fireballs — spotted location",
  fireballSpotted: "Spotted location",
  closeApproach: "Close Approach Data (CAD)",
  events: "Events",
  riskCards: "Risk Cards",
  focusedMeteor: "Focused Meteor",
  sentry: "Sentry Impact Risk (Sentry)",
  sbdb: "Small-Body Database (SBDB)",
  cad: "Close Approach Data (CAD)",
  loadingFeeds:
    "Loading Sentry Impact Risk, Close Approach Data (CAD), Fireballs, and Small-Body Database (SBDB)…",
  liveSky: "Live Sky Position (Horizons)",
  horizons: "JPL Horizons",
  apparentCoords: "Apparent Coordinates (RA/Dec)",
  rightAscension: "Right Ascension (RA)",
  declination: "Declination (Dec)",
  apparentMagnitude: "Apparent Magnitude (V)",
  geocentricDistance: "Geocentric Distance (Δ)",
  distanceAu: "Distance (AU)",
  lightTravel: "Light Travel Time",
  constellation: "Constellation (approx.)",
} as const;
